[theme]
primaryColor = "#64A70B"              # lime-green accent
backgroundColor =  "#EDEEEF"          # Excelitas Cool Grey 100%
secondaryBackgroundColor = "#D2D5D7"  # Excelitas Cool Grey 75%
textColor = "#000000"                 # crisp white
font = "sans serif"
